version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "4535:5000"  # Map external port 4535 to internal container port 5000
    volumes:
      - .:/app  # Mount the current directory as a volume inside the container
      - ./pos_system.db:/app/pos_system.db  # Persist the SQLite DB file on the host machine
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_db
    volumes:
      - ./pos_system.db:/app/pos_system.db  # Persist the SQLite DB file on the host machine
    restart: always
