version: '3.8'

services:
  web:
    build: .
    container_name: Angadi_flask_app
    ports:
      - "4535:5000"  # Map external port 4535 to internal container port 5000
    volumes:
      - .:/app
      - ./pos_system.db:/app/pos_system.db
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - custom_network

  db:
    image: nouchka/sqlite3:latest
    container_name: angadi_sqlite_db
    volumes:
      - ./pos_system.db:/app/pos_system.db
    restart: always
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"  # New subnet range to avoid overlap
